### ISSUE TITLE
Switch to in-place `criterion_and_gradient!`

### ISSUE THREAD

**Issue by p-gw** [p-gw/FactorRotations.jl#57]
As noted in #54, a switch to an in-place gradient calculation could speed up performance by avoiding array allocations:

> But if in the long run you consider switching to a unified in-place _criterion_and_gradient!(grad::Union{AbstractVector, Nothing}, ...)_, which would skip gradient calculation if _grad === nothing_, this PR would be irrelevant.
> Right now the profiling shows that for a 62x24 matrix rotation ~10% is spent in the array allocation (both gradient calculation and projection).

**Comment by alyst** [comment]
This is a profiling of a varimax rotation of 782x32 matrix:
![image](https://github.com/p-gw/FactorRotations.jl/assets/348591/91da1935-3abc-47b8-8d63-06ea2c557a65)

Looks like in gradient calculation 33% of the time is spent in array allocation, 33% in copying.
